### PR TITLE
Assembler 

### PR DESCRIPTION
**Pull request by ryze312**
Adds a compiler for Vixen assembly language (VASM), the usage is as follows:
```
vasm source_file rom.bin
```

This will take the source from `source_file` and write compiled ROM to `rom.bin`.

### CODE REVIEW

**Comment by ryze312** [comment]
Please do a squish and rebase

**Comment by starscouts** [comment]
It's called squash silly, not squish

**Comment by ryze312** [comment]
> It's called squash silly, not squish

I'll still call it squish, even if it sounds silly

**Review by starscouts — COMMENTED** [review]
The code looks good so far, however some `FIXME`s persist. Additionally, I would suggest enabling pedantic mode for Clippy and fix any warnings that arise.

I will approve this PR once `FIXME`s are fixed (or removed if they are unnecessary) and after support for the `.include` macro and character literals (`#'a'`) is implemented. Extra features can come later.

**Review by starscouts — COMMENTED** [review]
Character literal implementations look correct, although we might want to limit it to Unicode characters instead of just ASCII, but that's going to be fine for now.

**Comment by ryze312** [comment]
> We might want to limit it to Unicode characters instead of just ASCII

Unicode doesn't have a clear distinction on what character is, Rust's `char` is just a code point so if we parse it as is it might not do what you would expect.

See [char](https://doc.rust-lang.org/stable/core/primitive.char.html) documentation.

**Comment by starscouts** [comment]
Note that we expect ASCII control characters (such as CR, LF, ESC, etc...) to still be usable as character literals.

**Review by starscouts — APPROVED** [review]

**Comment by ryze312** [comment]
@starscouts Why did you remove `#[must_use]`?

**Comment by starscouts** [comment]
> @starscouts Why did you remove `#[must_use]`?

Clippy complained that it was useless

**Review by starscouts — CHANGES_REQUESTED** [review]
Just missing hardcoded/built-in constants as mentioned in #6 to cover the full feature set described by #9 and merge.

**Comment by ryze312** [comment]
> Just missing hardcoded/built-in constants 

Is there a list of those anywhere?

**Review by starscouts — APPROVED** [review]
This looks good to me. This pull request can be merged whenever you are ready.

**Pull request merged**
